services:
  postgres:
    image: postgres:16-alpine
    container_name: cloudsentinel-postgres

    environment:
      POSTGRES_DB: cloudsentinel
      POSTGRES_USER: cloudsentinel
      POSTGRES_PASSWORD: cloudsentinel

    ports:
      - "5433:5432"

    volumes:
      - cloudsentinel_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U cloudsentinel -d cloudsentinel"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.8.0
    container_name: cloudsentinel-keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-change-me-local-only}
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./keycloak/cloudsentinel-realm.json:/opt/keycloak/data/import/cloudsentinel-realm.json:ro
      - cloudsentinel_keycloak_data:/opt/keycloak/data
    restart: unless-stopped

volumes:
  cloudsentinel_postgres_data:
  cloudsentinel_keycloak_data:
