import React,{useEffect,useMemo,useState}from"react";
const api=p=>fetch(p).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});
const n=x=>new Intl.NumberFormat("en-IN").format(Number(x||0));
function App(){const[s,setS]=useState(null),[a,setA]=useState([]),[f,setF]=useState([]),[page,setPage]=useState("Overview"),[q,setQ]=useState(""),[err,setErr]=useState("");
const load=()=>Promise.all([api("/api/v1/dashboard/summary"),api("/api/v1/alerts"),api("/api/v1/findings")]).then(x=>{setS(x[0]);setA(Array.isArray(x[1])?x[1]:x[1].items||[]);setF(Array.isArray(x[2])?x[2]:x[2].items||[]);setErr("")}).catch(()=>setErr("API unavailable — start FastAPI on port 8000"));useEffect(load,[]);
const rows=(page==="Findings"?f:a).filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));let sev=s?.findings?.by_severity||{},src=s?.findings?.by_source||{},risk=s?.risk?.average_finding_risk||0,score=Math.max(0,Math.round(100-risk));
return <div className="app"><aside><div className="logo">◆</div><h2>CloudSentinel</h2><small>Security Operations</small><nav>{["Overview","Findings","Alerts","Integrations"].map(x=><button className={page===x?"active":""} onClick={()=>setPage(x)} key={x}>{x}</button>)}</nav><footer>● Platform healthy<br/><span>AWS • ap-south-1</span></footer></aside><main><header><div>Cloud Security / <b>{page}</b></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search..."/><button onClick={load}>↻</button></header>{err&&<div className="error">{err}</div>}{page==="Overview"&&<Overview s={s} score={score} sev={sev} src={src} a={a}/>} {page==="Findings"&&<Listing title="Findings" rows={rows} finding/>}{page==="Alerts"&&<Listing title="Alerts" rows={rows}/>} {page==="Integrations"&&<Integrations s={s}/>}</main></div>}
function Overview({s,score,sev,src,a}){return <section><p className="eyebrow">SECURITY POSTURE</p><h1>Cloud security overview</h1><p className="muted">Live AWS security visibility from CloudSentinel.</p><div className="cards"><Card t="Security Score" v={score} h="out of 100"/><Card t="Critical Findings" v={s?.findings?.critical} h="current"/><Card t="High Findings" v={s?.findings?.high} h="current"/><Card t="Open Alerts" v={s?.alerts?.open} h="response queue"/></div><div className="grid"><Panel title="Findings by severity"><Bars data={sev}/></Panel><Panel title="Findings by source"><Bars data={src}/></Panel></div><div className="grid"><Panel title="Risk profile"><div className="big">{Number(s?.risk?.average_finding_risk||0).toFixed(1)}<small>/100 average risk</small></div><div className="track"><i style={{width:(s?.risk?.average_finding_risk||0)+"%"}}/></div><p className="muted">Maximum risk: <b>{s?.risk?.max_finding_risk||0}</b></p></Panel><Panel title="Priority alerts"><Table rows={a.slice(0,6)}/></Panel></div></section>}
function Card({t,v,h}){return <div className="card"><small>{t}</small><strong>{v==null?"—":v}</strong><span>{h}</span></div>}
function Panel({title,children}){return <div className="panel"><h3>{title}</h3>{children}</div>}
function Bars({data}){let m=Math.max(...Object.values(data||{}).map(Number),1);return <div>{Object.entries(data||{}).map(([k,v])=><div className="bar" key={k}><span>{k.replaceAll("_"," ")}</span><b>{n(v)}</b><i><em style={{width:Number(v)/m*100+"%"}}/></i></div>)}</div>}
function Table({rows,finding}){return <div className="table"><div className="thead"><span>Title</span><span>Source</span><span>Severity</span><span>Risk</span></div>{rows.map(x=><div className="tr" key={x.finding_id||x.alert_id}><span><b>{x.title||x.rule_name}</b><small>{x.finding_id||x.alert_id}</small></span><span>{x.source}</span><span className={"sev "+x.severity}>{x.severity}</span><span>{Number(x.risk_score||0).toFixed(0)}</span></div>)}</div>}
function Listing({title,rows,finding}){return <section><p className="eyebrow">{finding?"EXPOSURE INVENTORY":"RESPONSE CENTER"}</p><h1>{title}</h1><p className="muted">Search and review CloudSentinel records.</p><div className="panel"><Table rows={rows} finding={finding}/></div></section>}
function Integrations({s}){let items=["GuardDuty","Security Hub","Inspector","Macie","AWS Config","CloudTrail","IAM"];return <section><p className="eyebrow">CONNECTIVITY</p><h1>Integrations</h1><p className="muted">AWS service coverage and normalized finding intake.</p><div className="integrations">{items.map(x=><div className="integration" key={x}><b>{x}</b><span>● Connected</span></div>)}</div><div className="panel"><h3>Commercial adapters</h3><div className="integrations">{["Wiz","Prisma Cloud / Cortex Cloud","CrowdStrike Falcon Cloud"].map(x=><div className="integration" key={x}><b>{x}</b><small>Mock adapter • credential-safe</small></div>)}</div></div></section>}
export default App;